all: make-versions test-built-container

make-versions:
	./test-make-versions-file -g

test-built-container:
	./test-test-built-container -g

clean:

.PHONY: all clean make-versions test-built-container
