#!/bin/bash

# Test presence of Dockerfile
if [ ! -f Dockerfile ] ; then
	echo "No Dockerfile !" >&2
	exit 1
fi

# Set grep & sed commands
if [ -z "$MAKE_VERSIONS_GREP" ] ; then
	MAKE_VERSIONS_GREP=grep
fi
if [ -z "$MAKE_VERSIONS_SED" ] ; then
	MAKE_VERSIONS_SED=sed
fi

$MAKE_VERSIONS_GREP '^[[:space:]]*ENV[[:space:]]*[A-Z]*_VERSION*' Dockerfile | $MAKE_VERSIONS_SED -e 's/^[[:space:]]*ENV[[:space:]]*\([A-Z]*_VERSION\)[[:space:]]*=[[:space:]]*\(.*\)$/\1=\2/' >PhenoMeNal_Versions.txt
